config/routes.rb
Rails.application.routes.draw do
 
  resources :items

  root to: "items#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

	validates :name, presence: true

	def total_price
		quantity * price if quantity.present? && price.present?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		if @item.save
			redirect_to items_path, notice: 'Item successfully created'
		else
			flash.now[:error] = @item.errors.full_messages.to_sentence
			render :new
		end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			redirect_to items_path
		else
			render :edit
		end
	end

	def destroy
		@item = Item.find(params[:id])
		if @item.destroy
			redirect_to items_path, notice: 'Successfull deleted'
		else
			redirect_to items_path, notice: @items.errors.full_messages.to_sentence
		end
	end

	private

	def item_params
		params.require(:item).permit(:name, :description, :quantity, :price)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= form_for @item do |f| %>
	<%= f.label 'Name' %>
	<%= f.text_field :name %>
	<br/>

	<%= f.label 'Descrition' %>
	<%= f.text_area :description %>
	<br/>

	<%= f.label 'Quantity' %>
	<%= f.text_field :quantity %>
	<br/>

	<%= f.label 'Price' %>
	<%= f.text_field :price %>

	<br/>
	<%= f.submit 'Save' %>
<% end %>

app/views/items/index.html.erb
<br/>

<div class="row"> 
  <%- flash.each do |key, value| %>
   <div class="alert alert-info">
    <%= value %>
   </div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-10">
    <h1>Items</h1>
  </div>

  <div class="col-md-2">
    <%= link_to "Create Item", new_item_path, class: 'btn btn-primary pull-right btn-header' %>
  </div>
</div>

<div class="row">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th> 
        <th>Quantity</th> 
        <th>Price</th> 
        <th>Total Price</th>
        <th>Actions</th> 
      </tr>
    </thead>
    <tbody>
      <%- @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.description %></td> 
          <td><%= item.quantity %></td>
          <td><%= item.price %></td>
          <td><%= item.total_price %></td>
          <td>
            <%= link_to "Edit", edit_item_path(item.id), class: 'btn btn-info' %>
            <%= link_to "Delete", item_path(item.id), method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/items/new.html.erb
<br/>

<div class="row"> 
  <%- flash.each do |key, value| %>
	 <div class="alert alert-info">
	 	<%= value %>
	 </div>
  <% end %>
</div>

<%= form_for @item do |f| %>
	<%= f.label 'Name' %>
	<%= f.text_field :name %>
	<br/>

	<%= f.label 'Descrition' %>
	<%= f.text_area :description %>
	<br/>

	<%= f.label 'Quantity' %>
	<%= f.text_field :quantity %>
	<br/>

	<%= f.label 'Price' %>
	<%= f.text_field :price %>

	<br/>
	<%= f.submit 'Save' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thegreyshoppe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>